### PR TITLE
Compatibility with rails 3+

### PR DESCRIPTION
**Pull request by sobrinho**

### CODE REVIEW

**Comment by fnando** [comment]
OMG! Thanks! 

I think it makes sense converting this into a gem. I'll do this later today.

**Comment by sobrinho** [comment]
Thanks!

We have a really really really old project using this plugin and we are going to upgrade it to rails 3 and latter to rails 4! :)

**Comment by sobrinho** [comment]
Ping :)

**Comment by fnando** [comment]
Totally forgot. Soon, I promise.

**Pull request closed without merging**
